using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wind_up_Zeno
{
    internal static class ClassRoom
    {
        internal static class Macros
        {
            internal static readonly List<string> Menu = new List<string> {
                "There is a way to make your own personalized menu for jobs, settings, emotes, macros, etc, using:\r\n- 2 hotbars\r\n- Some macros\r\n- Jobs without soulstone (for store menus)\r\n\r\nHelps to have screen more clean and have more free hotbars.\r\n\r\n:warning: Game don't let you run more than one macro at same time, when this happens game cancel your current macro and run the new one. :warning:\r\n:warning: If you running a crafting macro and uses the menu YOU going cancel the crafting macro :warning:\r\nYou can use `/macrolock` on your crafting macros for prevent it.\r\n\r\n(Recomended hide unassigned slots.)",
                "https://i.postimg.cc/ZR1ntgmV/menugif.gif",
                "## _Part 1_\r\n# Understanding\r\nBasicaly we use one shared hotbar as main menu for store macros, on this macros we going handle the other hotbar that need be non-shared hotbar.\r\nThis menu works making a copy of hotbars, so we need make this hotbar on our useless job.\r\nFor this we going use jobs without stones for save the menus on it hotbars.\r\n\r\n_On next GIF you can see how is copying hotbars from lancer job._",
                "https://i.postimg.cc/2SmqSPZt/muestra-menu.gif",
                "## _Part 2_\r\n#  Setting hotbars\r\nBefore starting be sure you knows what hotbars you going use and remember what number is each. (you can see on `Main menu > System > HUD Layout` or type `/hudlayout`).\r\nOn this guide i going use hotbars 5 and 8.\r\n\r\nNext is go to `Main menu > System > Character Configuration > Hotbar Settings > Sharing`.\r\nHere set your static menu bar as shared and variable menu unshared.\r\n\r\n__ _(If your variable menu is shared hotbar, the copy macro it won't work)_ __",
                "https://i.postimg.cc/x1RXJtG1/ffxiv-dx11-m-Vo-Idrbt4-C.png",
                ".\r\nWith this done you can start filling the hotbars of any job with no stone.\r\nFor this just remove the Soulstone from character menu.\r\nIf you can't can be for 2 reasons:\r\n- This job have no class xD\r\n- Your weapon is only for a specific job.\r\n\r\n## _Part 3_\r\n# Macros\r\nWe can put this macros on both menus, but all need __edit only the variable menu__.\r\nThe comand we going use is `/hotbar copy FROM X TO Y`\r\n- FROM = Job that have the hotbar to copy.\r\n- X      = Number of the hotbar to copy.\r\n- TO   = Job where paste, we going use the keyword `current` that uses current job.\r\n- Y      = Number of hotbar where paste. This should be ever variable menu.\r\n\r\n_Example_\r\n_Copying pugilist hotbar 3 to your current job hotbar 8_\r\n```\r\n/hotbar copy PGL 3 current 8\r\n```\r\n\r\nIn addition we can add a timer for wait some seconds then clear the hotbar for have the menu \"closed\"\r\n_ Game don't let you run more than one macro at each time, so game cancel your current macro and run the new one _\r\n_example_\r\n```\r\n/hotbar copy PGL 3 current 8\r\n/wait 5\r\n/hotbar remove 8 all\r\n```\r\n\r\nOr we can hide the hotbar and show each time we need, but this add one more line to all menu macros because we need show again.\r\n```\r\n/hotbar display 8 on\r\n/hotbar copy PGL 3 current 8\r\n/wait 5\r\n/hotbar display 8 off\r\n```",
                "https://i.postimg.cc/W3DzyVBd/mex.png"
            };


            internal static readonly List<string> UsefulMacros = new List<string>
            {
                "# __Useful macros for daily life in Eorzea__\r\n \r\n## Non-combat macros\r\n \r\n### :blue_car: Ride any pillion of the current target\r\n```\r\n/macroerror off\r\n/ridepillion <2>\r\n/ridepillion <3>\r\n/ridepillion <4>\r\n/ridepillion <5>\r\n/ridepillion <6>\r\n/ridepillion <7>\r\n/ridepillion <8>\r\n/micon \"Jump\" general\r\n```\r\n\r\n### :man_walking: Follow nearest player\r\n```\r\n/targetpc\r\n/follow\r\n/micon \"Flex\" emote\r\n```\r\n### :man_in_manual_wheelchair:  Sprint macro\r\nMount + Sprint + Peloton + Fate Level Sync\r\n```\r\n/macroerror off\r\n/actionerror off\r\n/ac \"Mount Roulette\"\r\n/ac \"Sprint\"\r\n/ac \"Peloton\"\r\n/levelsync on\r\n/micon \"Sprint\"\r\n```\r\n### :man_cook: Job change\r\nUseful with gatherers for activate buffs or for use difrent titles or glamours on jobs.\r\n\r\n:fishing_pole_and_fish: (Fisher example)\r\n```\r\n/micon \"Abroader Otter\" minion\r\n/gs equip XX YY\r\n/wait 1\r\n/ac \"Collect\"\r\n/title set \"Of the Irresistible Lure\"\r\n```\r\nXX = number of job on your gearset\r\nYY = number of glamor plate to apply (OPTIONAL)\r\n\r\nAlso you can make a macro for copy the crafters hotbars then you can have same skill order on each craftrer:\r\nOn the example Carpenter have all skills sorted on hotbars 1, 2, 3 and 4\r\n```\r\n/micon 25 gearset\r\n/gs equip 25 <wait.1>\r\n/hotbar copy crp 1 current 1\r\n/hotbar copy crp 2 current 2\r\n/hotbar copy crp 3 current 3\r\n/hotbar copy crp 4 current 4\r\n/title set \"Of Countless Crafts\"\r\n```\r\n### :shushing_face: Mute game (on/off)\r\n```/mastervolume```",
                "### :shaking_face: Text for that quests where you need type something\r\n||```\r\n/micon \"Interject\"\r\n/s Mol coffee break free kupo nuts dream bigger his whiskers, snae ling Please, Feo Ul, I need you O loveliest of branches, please grant me your succor! Amid the Flowers <wait.1>\r\n/s Tataru Anogg Uhm Ala Lali-ho Sushena Kenn Gyuf coo everything will be fine Itomaki Ismella rekindle the flames of hope With the Wind High as Honor Now Fall <wait.1>\r\n/s  I have a favor to ask Pretty Please, Emet-Selch Y'shtola carrot of happiness You misunderstand. I come in peace. Greetings and salutations! Well met! <wait.1>\r\n/s Noughts and Crosses my friend Your god is come Ellie! la-hee inspection GRRR! allin tuta Suzume come hells or high water Egg Hunt tuktu going my way Doubt the truth <wait.1>\r\n/s Guydelot Deftarm! Fray! Beaver Gaia Don't give up! Wake up! Lad Kenn smoked fish from Isari Is anyone around here? Wings Unbending Hail fellow well met! <wait.1>\r\n```||\r\n### :star2: Sheathed weapon shiny\r\n```\r\n/bm\r\n/groundsit\r\n/micon \"Minion of Light\" minion\r\n```\r\n\r\n### :see_no_evil: Sumoner pets are anoying\r\n```\r\n/petsize all small\r\n```",
                "## :crossed_swords: Combat macros\r\n\r\n### :hand_splayed: Action cast\r\n`/ac \"action or skill name\" <XX>` (<XX> its a placeholder and is optional)\r\nFor use Duty Action I and II => `/gaction \"Duty Action I\" <XX>` (<XX> its a placeholder and is optional)\r\n\r\n__Placeholders__\r\n- <t> target (used if you put nothing)\r\n- <mo> Mouse over\r\n- <f> Focus\r\n- <tt> Target of terget\r\n- <X> X = Number of party member\r\n- <lt> Last target\r\n\r\n__Mark placeholders__\r\n- <attackX> X = Target attack marks (1 to 8) \r\n- <bindX> X = Target bind marks (1 to 3) \r\n- <stopX> X = Target stop marks (1 to 2) \r\n- <square> Target square mark\r\n- <circle> Target circle mark\r\n- <cross> Target cross mark\r\n- <triangle> Target triangle mark\r\n\r\n:mouse_three_button: _Mouse over or current target example:_\r\nGives prio to mouse over, if have nothing on mouse over then do target cast.\r\n```\r\n/macroerror off\r\n/actionerror off\r\n/ac \"Cure\" <mo>\r\n/ac \"Cure\"\r\n/micon \"Cure\"\r\n```\r\n### :orange_circle: Instant ground AoE\r\nYou need have enabled `Press action twice to execute` that is located on `Main menu > System > Character Configuration > Control Settings > Target`.\r\n```\r\n/ac \"Asylum\"\r\n/ac \"Asylum\"\r\n/micon \"Asylum\"\r\n```\r\n\r\n### :clock9: Share recast timer\r\n```\r\n/p Swiftcast: <recast.Swiftcast>\r\n```",
                "## :frame_photo: Macro icons\r\n```\r\n/micon \"XXX\" YYY\r\n```XXX name\r\nYYY category\r\n\r\n### Categories:\r\n\r\n- Skills `/micon \"Cure\"`  (for job skills you don't need type category)\r\n- BLU skills `/micon \"Pom Cure\" blueaction`\r\n- Emotes `/micon \"Blush\" emote`\r\n- Chocobo skills `/micon \"Choco Regen\" companion`\r\n- Pet actions `/micon \"Heel\" pet`\r\n- Mounts `/micon \"Juedi\" mount`\r\n- Minions `/micon \"Bacon Bits\" minion`\r\n- Gearsets `/micon 12 gearset` (the number of job in gearset, you can open with `/gearset` )\r\n- ClassJobs `/micon \"White Mage\" classjob` (same as gearset but with text)\r\n- Items `/micon \"Versatile Lure\" item` (you need have the item in your inventory)",
                "## SUM/SCH Pet Glamours\r\nWe can change the glamour of pets using this command: `/egiglamour SUMMON GLAMOUR`\r\nIf  you have summoned you need resummon for see the changes.\r\nAll changes are loged on General chat.\r\n\r\n### SUM\r\nSummons:\r\n- Carbuncle\r\n- Garuda-Egi\r\n- Titan-Egi\r\n- Ifrit-Egi\r\n\r\nGlamours:\r\n- Carbuncle\r\n- Emerald Carbuncle\r\n- Topaz Carbuncle\r\n- Ruby Carbuncle\r\n- Garuda-Egi\r\n- Titan-Egi\r\n- Ifrit-Egi\r\n_Examples_\r\n`/egiglamour \"Carbuncle\" \"Ifrit-Egi\"`\r\n`/egiglamour \"Ifrit-Egi\" \"Ruby Carbuncle\"`\r\n`/egiglamour \"Garuda-Egi\" \"Emerald Carbuncle\"`\r\n\r\n### SCH\r\nOnly have one:\r\n`/egiglamour Eos\" \"Selene\"`\r\n\r\nFor remove glamors put no one glamour: `/egiglamour \"Carbuncle\"`"
            };

            internal static readonly List<string> HUD = new List<string>
            {
                "## HUD edit\r\nWe can edit HUD typing `/hudlayout` or going to `Main menu > System > HUD Layout`.\r\n### Useful tips\r\n- For enable/disable any element you can right click on it when editing HUD.\r\n- For precise placement you can select that you want move and use keyboard numeric pad arrows.\r\n- If you have something overlaped and you can't select just use the list: `Current UI Element`.\r\n- You can make biger or smaller any element also edit transparency.\r\n- Save your current UI on other slot as backup before you edit if you can.\r\n- Remember do a backup on character selection menu\r\n# How to make target cast bar bigger\r\nWe can split target HP bar, Cast bar and Status. Then we can edit each size.",
                "https://i.postimg.cc/kMzCHrh2/ffxiv-dx11-k-WJ33g-JDQJ.png",
                "https://i.postimg.cc/CxVgFG0Y/b1d6e0f9ff27ae7b147a1027661a435c.png",
                "## HUD Macros\r\n### Alternate the visivility of Hotbars\r\n_ __ All settings that can be set on: `on` or `off`, you can use `[on/off]` for elternate __ _\r\n\r\n```\r\n/hotbar display XX [on/off]\r\n```\r\n```\r\n/hud \"HotbarXX\" [on/off]\r\n```\r\nXX = the number of hotbar you want alternate\r\n\r\n### Change HUD Layout\r\n```\r\n/hudlayout X\r\n```\r\nX = number of layout to select (1 to 4)\r\n\r\n### Alternate the visivility of UI elements\r\n```\r\n/hud \"XXX\" [on/off]\r\n```\r\n\r\nXXX Element of UI\r\nList is bit long, you can see the name of elements while you are editing HUD or look [Lodestone List](<https://na.finalfantasyxiv.com/lodestone/playguide/db/text_command/be2b72ee3f6/>)\r\n_quotation marks are mandatory if its more than one word_\r\nExample:\r\n`/hud \"Party List\" [on/off]`\r\n\r\nExample of HUD alternate macro\r\n```\r\n/hud \"Hotbar1\" [on/off]\r\n/hud \"Hotbar2\" [on/off]\r\n/hud \"Hotbar3\" [on/off]\r\n/hud \"Hotbar4\" [on/off]\r\n/hud \"Gil\" [on/off]\r\n/hud \"param\" [on/off]\r\n/hud \"plist\" [on/off]\r\n/hud \"JobGauge1\" [on/off]\r\n/hud \"JobGauge2\" [on/off]\r\n/hud \"ServerInfo\" [on/off]\r\n/hud \"ExpBar\" [on/off]\r\n/hud \"sfx\" [on/off]\r\n/hud \"sienh\" [on/off]\r\n/hud \"sicenh\" [on/off]\r\n/hud \"dlist\" [on/off]\r\n```\r\nThis macro hide/show:\r\n-  4 hotbars\r\n- Gil\r\n- HP/Mana bars\r\n- Party list\r\n- Job gauges\r\n- Server info (clock, server bar)\r\n- Experience bar\r\n- Duty List (quests, fates)\r\n- Status info bars (Buffs debufs)"

            };

            internal static readonly List<string> RetainerBasics = new List<string>
            {
                "## Retainer Ventures:\r\n### Hunting/Mining/Botany/Fishing\r\n\r\n* Hunting => War/Magic jobs bring monster drop items, this mean 0 bicolor gems waste on materials.\r\n* Mining => bring miner materials also shards and crystals.\r\n* Botany => bring botanist materials also shards and crystals.\r\n* Fisher only brings fishes... (is not bad at all)\r\nTakes from 45 min to 1 hour an the amount depends on our retainer stats.\r\nReference for amount/stats:\r\n[Hunting](<https://ffxiv.gamerescape.com/wiki/Hunting_Exploration>)\r\n[Mining](<https://ffxiv.gamerescape.com/wiki/Mining_Exploration>)\r\n[Botany](<https://ffxiv.gamerescape.com/wiki/Botany_Exploration>)\r\n[Fishing](<https://ffxiv.gamerescape.com/wiki/Fishing_Exploration>)\r\n\r\n### Quick Exploration\r\nAll jobs can bring random gear, venture coffer and housing items or 1 crystal.\r\nThis is the best way for rise retainer level and ventures.\r\n__For farm ventures we only need exchange the gear that retainer bring for company seals then seals for ventures.__\r\nQuick Exploration have no gear restrictions and only matters retainer level.\r\nTakes 1 hour, unlocked at retainer lvl 10.\r\nAlso can bring items from 1.X that are obtainable. ([List](<https://ffxiv.gamerescape.com/wiki/Quick_Exploration>))\r\n\r\n### Woodland,  Highland, Field, or Waterside Exploration\r\nWith this we going get bit gil and random materials with with a low chance to get valuable minions or items.\r\n[ Highland Exploration](<https://ffxiv.gamerescape.com/wiki/Highland_Exploration>)\r\n[ WoodlandExploration](<https://ffxiv.gamerescape.com/wiki/Woodland_Exploration>)\r\n[ Field Exploration](<https://ffxiv.gamerescape.com/wiki/Field_Exploration>)\r\n[ Waterside Exploration](<https://ffxiv.gamerescape.com/wiki/Waterside_Exploration>)\r\nTakes 18 hours.",
                "## Gathering Retainer Melds\r\nFor reach the stats desired on retainers and get more materials on each venture we going need meld some materia on retainer gear.\r\n\r\nCurrently the best one is 4905 breakpoint because go more high means pentameld and we only going rise one item. with this breakpoint retainers can carry:\r\n\r\nMiner and Botany.\r\n* lvl 100 - 20 items\r\n* lvl 94 to 99 - 30 items\r\n* lvl 90 to 93 - 40 items\r\n* inferior levels 50 items\r\n\r\n[i690 Retainer - 4905 Breakpoint. With __old__ materias.](<https://ffxivteamcraft.com/gearset/2AtHNL5oj0LLG7DOpumH>)\r\n[i690 Retainer - 4905 Breakpoint. With __new__ materias.](<https://ffxivteamcraft.com/gearset/MsjCsTXphYeItymOBYU5>)"
            };



        }
    }
}
